#!/usr/bin/env node
// Regenerate src/psl/psl-data.ts from the vendored src/psl/public_suffix_list.dat.
//
// tsc does not copy .dat files into dist/, so the list ships as a generated TypeScript module: one
// ASCII rule per line, IDN labels converted to punycode (A-labels) with node:url's domainToASCII,
// split into the ICANN and PRIVATE sections.
//
// To refresh the list:
//   curl -fsS https://publicsuffix.org/list/public_suffix_list.dat \
//     -o packages/auth-checks/src/psl/public_suffix_list.dat
//   node packages/auth-checks/scripts/gen-psl.mjs
// `--check` exits 1 when psl-data.ts is stale (a unit test runs it).

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { domainToASCII } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const datPath = join(here, '..', 'src', 'psl', 'public_suffix_list.dat');
const outPath = join(here, '..', 'src', 'psl', 'psl-data.ts');

/** One label to its A-label form; ASCII labels (and '*') are kept as they are. */
function asciiLabel(label) {
  // eslint-disable-next-line no-control-regex -- the ASCII range is the point
  if (/^[\x00-\x7f]*$/.test(label)) return label;
  const ascii = domainToASCII(label);
  if (ascii === '' || ascii.includes('.')) throw new Error(`cannot convert PSL label "${label}"`);
  return ascii;
}

function asciiRule(rule) {
  const exception = rule.startsWith('!');
  const body = exception ? rule.slice(1) : rule;
  const converted = body.split('.').map(asciiLabel).join('.');
  return exception ? `!${converted}` : converted;
}

export function generate(dat) {
  const sections = { icann: [], private: [] };
  let section;
  let version = 'unknown';
  for (const rawLine of dat.split(/\r?\n/)) {
    const line = rawLine.trim();
    const v = /^\/\/ VERSION: (\S+)/.exec(line);
    if (v !== null) version = v[1];
    if (line === '// ===BEGIN ICANN DOMAINS===') section = 'icann';
    else if (line === '// ===BEGIN PRIVATE DOMAINS===') section = 'private';
    else if (line.startsWith('// ===END')) section = undefined;
    if (line === '' || line.startsWith('//') || section === undefined) continue;
    // "Each line is only read up to the first whitespace" (publicsuffix.org/list).
    const rule = line.split(/\s/)[0];
    sections[section].push(asciiRule(rule.toLowerCase()));
  }
  return [
    '// GENERATED by scripts/gen-psl.mjs from public_suffix_list.dat. Do not edit by hand.',
    '// The Public Suffix List is subject to the Mozilla Public License, v. 2.0',
    '// (https://mozilla.org/MPL/2.0/); see the header of public_suffix_list.dat.',
    '',
    `export const PSL_VERSION = '${version}';`,
    '',
    `/** ${sections.icann.length} rules from the ICANN section, one per line, A-labels. */`,
    `export const ICANN_RULES = \`\n${sections.icann.join('\n')}\n\`;`,
    '',
    `/** ${sections.private.length} rules from the PRIVATE section, one per line, A-labels. */`,
    `export const PRIVATE_RULES = \`\n${sections.private.join('\n')}\n\`;`,
    '',
  ].join('\n');
}

const out = generate(readFileSync(datPath, 'utf8'));
if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(outPath, 'utf8');
  } catch (err) {
    console.error(`cannot read ${outPath}: ${err.message}`);
    process.exit(1);
  }
  if (current !== out) {
    console.error('psl-data.ts is stale: run node scripts/gen-psl.mjs');
    process.exit(1);
  }
  console.log('psl-data.ts is up to date');
} else {
  writeFileSync(outPath, out);
  console.log(`wrote ${outPath}`);
}
